networks:
    default:
        external: true
        name: k-core

volumes:
    mysql_data:
        external: true
        name : k_mysql_data

services:
    mysql:
        image: mysql:${IMAGE_MYSQL_TAG}
        container_name: k-mysql
        restart: unless-stopped
        command: [ "mysqld",
                    "--character-set-server=utf8mb4",
                    "--collation-server=utf8mb4_unicode_ci",
                    "--bind-address=0.0.0.0" ]
        volumes:
           - mysql_data:/var/lib/mysql
        environment:
           MYSQL_ROOT_PASSWORD: mysql
           MYSQL_USER: wordpress
           MYSQL_PASSWORD: wordpress
           MYSQL_DATABASE: wordpress
        # ports:
        #     - "3306:3306"
